### ISSUE TITLE
Bijector not defined for FiniteGP

### ISSUE THREAD

**Issue by ElOceanografo** [willtebbutt/Stheno.jl#113]
I found this when trying to run the [Turing integration example](https://github.com/willtebbutt/Stheno.jl/blob/master/examples/turing_integration/binary_classification.jl).  When I attempted to sample from the model ([line 78](https://github.com/willtebbutt/Stheno.jl/blob/85d65fbf27873e9fa49b33358d95f3be72bf0ae6/examples/turing_integration/binary_classification.jl#L78)), the error below is produced.

Not sure if this belongs here or in Bijectors...I can open an issue there if that's more appropriate.

```julia
MethodError: no method matching bijector(::Stheno.FiniteGP{GP{Stheno.ZeroMean{Float64},Stheno.Scaled{Array{Float64,1},Stheno.Stretched{Array{Float64,1},EQ,typeof(identity)},typeof(identity)}},ColVecs{Float64,Array{Float64,2}},LinearAlgebra.Diagonal{Float64,FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}}})
Closest candidates are:
  bijector(!Matched::KSOneSided) at C:\Users\sam.urmy\.julia\packages\Bijectors\bHaf6\src\transformed_distribution.jl:58
  bijector(!Matched::Product{Discrete,T,V} where V<:AbstractArray{T,1} where T<:Distribution{Univariate,Discrete}) at C:\Users\sam.urmy\.julia\packages\Bijectors\bHaf6\src\transformed_distribution.jl:39
  bijector(!Matched::Product{Continuous,T,Tdists} where Tdists<:(FillArrays.Fill{T,1,Axes} where Axes) where T<:Distribution{Univariate,Continuous}) at C:\Users\sam.urmy\.julia\packages\Bijectors\bHaf6\src\compat\distributionsad.jl:16
  ...
in top-level scope at untitled:78
in sample at Turing\GMBTf\src\inference\Inference.jl:153
in #sample#1 at Turing\GMBTf\src\inference\Inference.jl:153 
in sample at Turing\GMBTf\src\inference\Inference.jl:163 
in #sample#2 at Turing\GMBTf\src\inference\Inference.jl:163
in Sampler at Turing\GMBTf\src\inference\hmc.jl:376 
in DynamicPPL.Sampler at Turing\GMBTf\src\inference\hmc.jl:384
in Turing.Inference.HMCState at Turing\GMBTf\src\inference\hmc.jl:609
in #HMCState#58 at Turing\GMBTf\src\inference\hmc.jl:612
in link! at DynamicPPL\9OFG0\src\varinfo.jl:697 
in _link! at DynamicPPL\9OFG0\src\varinfo.jl:700
in macro expansion at DynamicPPL\9OFG0\src\varinfo.jl:709 
in link at Bijectors\bHaf6\src\Bijectors.jl:118
```

**Comment by ElOceanografo** [comment]
For reference, running the following (copied from [here](https://github.com/TuringLang/Bijectors.jl/blob/d626f046b7f49160e22d597d2df6231413428180/src/transformed_distribution.jl#L53) and [here](https://github.com/TuringLang/Bijectors.jl/blob/9375adaafb1ce238ce6e7648b445ae63abc0b32f/src/compat/distributionsad.jl#L21)) before running the Turing model fixes the error:

```julia
Bijectors.bijector(d::Stheno.FiniteGP) = Identity{1}()
for T in (:VectorOfMultivariate, :FillVectorOfMultivariate)
    @eval begin
        Bijectors.bijector(d::Bijectors.$T{Continuous, <:Stheno.FiniteGP}) = Identity{2}()
    end
end
```

**Comment by willtebbutt** [comment]
Thanks for opening this. I'll try and take a look soon.

**Comment by nucklass** [comment]
Ran into a similar problem trying to use a logit link and bernoulli likelihood function. Is the above still the best solution to this?

**Comment by willtebbutt** [comment]
Hmm I guess.

@torfjelde do you know what's going on here?

**Comment by torfjelde** [comment]
Yeah, I'd say so. Not too long ago we removed the "default"-implementations, which was to just use `Identity` if we didn't recognize the distribution. Unfortunately that lead to a lot of silent bugs, hence we now require explicit implementation of `bijector`. And the above solution by @ElOceanografo is good:)

**Comment by willtebbutt** [comment]
Ah I see. @torfjelde what's the correct place to solve this? `Bijectors` has quite a lot of deps that I'm not keen to take on in `Stheno`, so I would prefer not to have to use it here just to solve Turing integration.

**Comment by torfjelde** [comment]
Well, I guess that kind means that we haven't done our job correctly, haha. The idea was for Bijectors.jl to be lightweight so that anyone who's using Distributions.jl wouldn't have any issues also depending on Bijectors.jl.

Are there any particular dependencies that makes this an issue?

With the exception of `Roots`, `NNlib` and `MappedArrays` I think we have essentially the same deps as Distributions.jl, no?

**Comment by willtebbutt** [comment]
Oh interesting. I actually hadn't noticed that / hadn't realised how lightweight all of those packages are.

I think I'm probably okay depending on `Bijectors` then. Could someone @torfjelde @ElOceanografo make a PR to Stheno to incorporate this?

A good place to add this would be another file in the `util` directory. Should be included below here in `Stheno.jl`:
https://github.com/willtebbutt/Stheno.jl/blob/f0f78aae68122d01b582296fea186715ecf88a96/src/Stheno.jl#L65

**Comment by willtebbutt** [comment]
Although, actually, @torfjelde is `bijector` defined for `AbstractMvNormal`, or just `MvNormal`? If it's the former then the `FiniteGP` could just subtype `AbstractMvNormal` instead of `ContinuousMultivariateDistribution`.

**Comment by torfjelde** [comment]
Ah, awesome!:)

And we're currently implementing it for `MvNormal`, but don't see any reason why we shouldn't do it for `AbstractMvNormal`, so we could at least make that change on Bijectors.jl's end :+1:

**Comment by willtebbutt** [comment]
Fantastic. I'll change things on my end, then hopefully it will "just work".

**Comment by willtebbutt** [comment]
Will leave this open until we've got new versions tagged.

**Comment by torfjelde** [comment]
Sweet! I'll make a PR for Bijectors.jl :+1:
