### ISSUE TITLE
Convex Constrained GP

### ISSUE THREAD

**Issue by pmcvay** [willtebbutt/Stheno.jl#131]
Is it possible to impose a convexity constraint on a Gaussian process? And is it possible to use Stheno to do this? I apologize if this is extremely off topic. I brand new to both GP's in general and Stheno.

**Comment by willtebbutt** [comment]
Hiya. Thanks for your interest.

Unfortunately it's pretty hard to impose those kinds of constraints on a GP. For example, there's a whole body of work on various ways to _almost_ impose monotonicity constraints, which can _nearly_ get you there. If you do stumble across a way to impose such a constraint, I would be very interested to hear about it!
