### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by rlrs** [willtebbutt/Stheno.jl#28]
The example in the readme doesn't run, and neither do any of the model zoo examples. I guess things have changed since they were made, like `eq()` being `EQ()`, but it would be nice to have some working basic examples of how to actually use the library. Especially for someone like me who is new to Julia, it's very hard to see how things work and fit together.

**Comment by willtebbutt** [comment]
Hi @rlrs . Apologies for the examples not working properly. I updated them recently to work with the updated API, but I've not gotten around to testing on machines other than my own. Would you be able to provide the error messages + stack traces so that I can understand what's going wrong?

**Comment by rlrs** [comment]
I can try. The first example in the readme gives me:
>UndefVarError: eq not defined

Changing `eq` to `EQ` (?),

> TypeError: in GP, in Tμ, expected Tμ<:Stheno.MeanFunction, got Type{Float64}
> Stacktrace:
>  [1] GP(::Float64, ::EQ, ::GPC) at C:\Users\Rasmus\.juliapro\JuliaPro_v1.1.1.1\packages\Stheno\CF2Cd\src\gp\gp.jl:24
>  [2] model at C:\Users\Rasmus\jgp\stheno_readme_example.jl:5 [inlined]
>  [3] model() at .\none:0
>  [4] top-level scope at none:0
> in expression starting at C:\Users\Rasmus\jgp\stheno_readme_example.jl:15

I also tried to run the `vanilla_noisy_regression.jl` example,

> UndefVarError: noise not defined
> Stacktrace:
>  [1] model() at C:\Users\Rasmus\jgp\vanilla_noisy_regression.jl:14
>  [2] top-level scope at none:0
> in expression starting at C:\Users\Rasmus\jgp\vanilla_noisy_regression.jl:26

I don't know if it's worth noting that `Pkg.installed()` tells me that I have version 0.1.1 of Stheno installed.

**Comment by willtebbutt** [comment]
Sounds to me like you've got an old version of Stheno installed. Could you try running
```julia
add Stheno#master
```
from the package manager, and re-running the examples?

**Comment by rlrs** [comment]
Alright, that was indeed the case. I guess that the package manager uses the latest Github release if you just `add Stheno`? 
> [8188c328] ↑ Stheno v0.1.1 ⇒ v0.1.1+ #master (https://github.com/willtebbutt/Stheno.jl.git)

I think it could be a good idea to put installation instructions in the readme. Thanks for the help!

**Comment by willtebbutt** [comment]
Great news, thanks for working through this. I'll definitely add some installation instructions to the readme.
