### ISSUE TITLE
All the Single-Output Kernels

### ISSUE THREAD

**Issue by willtebbutt** [willtebbutt/Stheno.jl#50]
Although the collection of base `Kernel`s in [kernels.jl](https://github.com/willtebbutt/Stheno.jl/blob/master/src/gp/kernel.jl) is significantly broader than it used to be, there's still quite a number of kernels that are listed in, for example, the GPML [manual](http://www.gaussianprocess.org/gpml/code/matlab/doc/manual.pdf) that aren't implemented here. A starting list of un-implemented kernels includes:

- [ ] Matern-7/2
- [ ] Generalised Matern
- [x] Cosine
- [ ] ArcCosine
- [ ] Piecewise Polynomial (Compact Support)
- [ ] Fractional Brownian Motion
- [ ] Underdamped Linear Langevin
- [ ] i-times integrated Wiener Process (we only support 0 and 1 I believe)
- [ ] Integrated OU
- [ ] Neural Net
- [ ] Periodic without DC component
- [ ] Cos
- [ ] Gabor

Please feel free to add any kernels that appear to be missing from this list and to open PRs that implement any of the above / anything that has been missed.

The `Internals` section of the docs provides an explanation of how to go about implementing new kernels within Stheno.

**Comment by BlackWingedKing** [comment]
Hi @willtebbutt 
Here's my implementation of cosine kernel with period parameter p
```julia
# Cosine kernel implementation 
# k(x,x1) = cos(pi*sqrt(sum((x-x1).^2))/p)
# p is the period length parameter
struct Cos{Tl<:Real} <: Kernel
    p::Tl
end

# Binary methods.
ew(k::Cos, x::AbstractVector{<:Real}, x1::AbstractVector{<:Real}) = cos.(pi.*ew(Euclidean(), x, x1) ./k.p)
pw(k::Cos, x::AbstractVector{<:Real}, x1::AbstractVector{<:Real}) = cos.(pi.*pw(Euclidean(), x, x1') ./k.p)

# # Unary methods.
ew(k::Cos, x::AbstractVector{<:Real}) = ones(eltype(x), length(x))
pw(k::Cos, x::AbstractVector{<:Real}) = pw(k, x, x')
```
It is as per internals.md and kernels.jl. I would also like to add the other kernels described above. If you agree with it I would like to open a PR 
Thank you.

**Comment by willtebbutt** [comment]
Hi @BlackWingedKing looks great! Please do open a PR and we can chat about this implementation further -- it looks like a solid first pass :)

**Comment by willtebbutt** [comment]
Closing this issue in favour of [this](https://github.com/theogf/KernelFunctions.jl/issues/44) `KernelFunctions.jl` issue. If you want to contribute, please do so there.

**Comment by yiyuezhuo** [comment]
Is it possible to use a kernel defined in `KernelFunctions.jl`? I tried to use `TransformedKernel` but got this:

```
MethodError: no method matching GP(::TransformedKernel{LinearKernel{Float64},FunctionTransform{var"#5#6"}}, ::GPC)
Closest candidates are:
  GP(!Matched::Stheno.Kernel, ::GPC) at /home/yiyuezhuo/.julia/packages/Stheno/ZsrnR/src/gp/gp.jl:71
  GP(::Any, !Matched::Stheno.Kernel, !Matched::GPC) at /home/yiyuezhuo/.julia/packages/Stheno/ZsrnR/src/gp/gp.jl:69
  GP(!Matched::Stheno.Kernel, ::Any, !Matched::GPC) at /home/yiyuezhuo/.julia/packages/Stheno/ZsrnR/src/gp/gp.jl:72

Stacktrace:
 [1] get_model at ./In[13]:3 [inlined]
 [2] get_model() at ./none:0
 [3] top-level scope at In[14]:1
 [4] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```

**Comment by willtebbutt** [comment]
It's not currently possible to do so -- I've been meaning to move Stheno over to the `KernelFunctions.jl` interface for a while, but I just haven't gotten around to doing so yet.
