### ISSUE TITLE
Question: GP regression with multi-dimensional inputs

### ISSUE THREAD

**Issue by nathbo** [willtebbutt/Stheno.jl#64]
I just wanted to play around with Stheno.jl for some simple GP regression problems, but I had trouble extending the very nice examples from [https://willtebbutt.github.io/Stheno.jl/stable/getting_started/](https://willtebbutt.github.io/Stheno.jl/stable/getting_started/) to multi-dimensional inputs. 

I have a minimal template of a standard GP regression on one-dimensional data here:
```julia
using Stheno

N = 100
X = randn(N)
y = randn(N)

f = GP(σ² * stretch(eq(), 1 / l), GPC())
f_posterior = f | (f(X, 0.05) ← y)
```
How can I modify this example in order to allow for multi-dimensional inputs
```julia
X = randn(N, d)
```
for some dimension `d`?

**Comment by willtebbutt** [comment]
Hi @nathbo . The thing to do is use the `ColVecs` structure:
```julia
X = randn(d, N)
x = ColVecs(X)
```
This keeps `X` stored internally as a dense matrix, and tells Stheno to interpret each column as a vector-valued input. The [Input Types](https://willtebbutt.github.io/Stheno.jl/dev/input_types/) documentation should be more thorough.

Let me know if you encounter any further issues :)

**Comment by nathbo** [comment]
Thanks for your help! I already thought that I probably missed some explanation, the Input Types documentation is exactly what I was looking for :) I will close the issue, and re-open if I have more questions/problems on the topic.
