### ISSUE TITLE
Mistake in the logdet

### ISSUE THREAD

**Issue by donhausk** [willtebbutt/Stheno.jl#70]
There is a mistake here:
`
function logpdf(f::FiniteGP, y::AbstractVector{<:Real})

    μ, C = mean(f), cholesky(Symmetric(cov(f)))

    return -(length(y) * log(2π) + logdet(C) + Xt_invA_X(C, y - μ)) / 2

end

`

Logdet(C) should not be divided by two since it is already the Cholesky derivative.

**Comment by willtebbutt** [comment]
Nope. Consider:
```julia
using LinearAlgebra

# Construct PSD matrix
A = randn(3, 3)
B = Symmetric(A * A' + I)

C = cholesky(B)

@assert logdet(C.U) * 2 ≈ logdet(C)
```

`logdet(cholesky(B))` computes the log determinant of the covariance matrix i.e. twice that of the triangular matrix stored in `cholesky(B)`

**Comment by donhausk** [comment]
Thanks for your fast answer! Yeah, but it should be `1/det(C)^0.5` and not `1/det(C) `. Therefore it must be 

> 0.5*logdet(C) = lodet(C.U)

https://en.wikipedia.org/wiki/Multivariate_normal_distribution
