### ISSUE TITLE
Multi-output GP?

### ISSUE THREAD

**Issue by rlrs** [willtebbutt/Stheno.jl#73]
The readme mentions multi-input and multi-output GPs, but I can't seem to find the functionality to handle multiple outputs. For now I'm just interested in independent outputs, so the most straightforward way might be to just maintain a list of GPs?

**Comment by willtebbutt** [comment]
Yup -- for independent GPs the best way is definitely to just maintain a list. Nothing is lost by doing this, so you should be fine.

By multi-output GPs the readme does mean things with correlated outputs. To handle this you'll again wind up maintaining a list of GPs, but they'll be correlated by construction. e.g.

```julia
# Declare independent GPs
gpc = GPC()
f1 = GP(eq(), gpc)
f2 = GP(eq(), gpc)

# Get some random weights and combine the GPs
A = randn(2, 2)
y1 = A[1, 1] * f1 + A[2, 1] * f2
y2 = A[1, 2] * f1 + A[2, 2] * f2
```
(You could also just store the above in a vector or something.

Ideally it would be possible to do the last line with a matrix multiply, but for some reason (not sure what) that doesn't currently work. If you do eventually want correlated outputs, I suggest the following hack:
```julia
gpc = GPC()
fs = [GP(eq(), gpc) for _ in 1:Q]
A = randn(P, Q)
ys = [sum(A[p, :] .* fs) for p in 1:P]
```

There's a strong possibility that a specific multi-output GP thing will be introduced into Stheno at some point soon, but it's not at the top of my priority list at the minute, so I can't give a time line on it. 

Is there any reason that maintaining independent GPs is a problem for you at this point, beyond it being a little bit ugly?

**Comment by rlrs** [comment]
Yes indeed, it was mostly for bookkeeping and avoiding some ugly loops for training etc., so I was hoping there was an easier way - but a list will work, thanks.
