### ISSUE TITLE
Parameter handling

### ISSUE THREAD

**Issue by willtebbutt** [willtebbutt/Stheno.jl#8]
#### Problem
There is currently no pleasant mechanism for handling parameters in one of Stheno's models. For example, the following is an example the current best way to handle parameters:
```julia
function model(θ::AbstractVector, gpc::GPC)
    f = GP(μ1(θ[1]), k1(θ[2:3]), gpc)
    g = GP(μ2(θ[4:6], k2(θ[7]), gpc)
    # some other code combining f, and g, and returning stuff.
end
```
The above code clearly doesn't scale well to problems where one requires a large number of parameters; each time one changes the `model` function there is the possibility that the way `θ` is indexed will need to change.

Note that this is a general problem in Machine Learning. Whatever solution I come up with here is a stop-gap on the road to a generic Julia solution being reached.

#### Specification
I propose to make model parameters from a combination of a `Vector` and an `Int`, and a method to retrieve the "next" set of free parameters.
```julia
struct ParVector{V<:AbstractVector}
    v::V
    n::Base.RefValue{Int}
    ParVector(v::V) where V<:AbstractVector = new{V}(v, Ref(0))
end
function getnext!(θ::ParVector, N::Int)
    out = θ.v[θ.n[]+1:θ.n[]+N]
    θ.n[] += N
    return out
end
```
Using the above type, one could then re-write the previous model as follows:
```julia
function model(θ::AbstractVector, gpc::GPC)
    f = GP(μ1(θ), k1(θ), gpc)
    g = GP(μ2(θ), k2(θ), gpc)
    # some other code combining f, and g, and returning stuff.
end
```
where each mean function and kernel simply calls the `getnext!` method of `θ` with whatever value of `N` is requires.

#### Implementation
The above forms the basics of an implementation, but the following details need to be worked out:
- How can one determine the appropriate length for `θ`?
- How can one efficiently specify initialisations for `θ`?
- How can it be made straightforward to determine which element of `θ` corresponds to what component in the model?
- What is the minimal interface a mean function / kernel (or other) needs to implement to take advantage of this type?

#### Issues
- It's not immediately clear how parameter tying would work here.

**Comment by datnamer** [comment]
Is "The Elephant in the Room" ie gradient based hyperparameter opt solved with zygote?

**Comment by willtebbutt** [comment]
I'm actually working on it as we speak. It's close to being done. I'm expecting to make a release in the next few days that supports AD with Zygote -- I've had to implement quite a number of custom primtives in Zygote.

**Comment by willtebbutt** [comment]
Resolved by Zygote compat with Stheno
